name: Build and Release SHC Binary

on:
  push:
    tags:
      - 'v*.*.*'   

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SHC
        run: sudo apt update && sudo apt install -y shc

      - name: Compile SH script
        run: |
          cd linux
          chmod +x iitdelhivpn.sh
          shc -f iitdelhivpn.sh -o iitdelhivpn

      - name: Create tarball
        run: |
          cd linux
          tar czvf iitdelhivpn.tar.gz iitdelhivpn
          
      - name: Upload shc to Release
        if: github.event_name != 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          files: linux/iitdelhivpn.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
